import enum, uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship as orm_relationship
from app.database import Base
from app.core.purpose import DataPurpose

def uuid_str(): return str(uuid.uuid4())
class Phase(str,enum.Enum): MIRROR="mirror"; DNA="dna"; COMPASS="compass"
class ExperienceType(str,enum.Enum): EMPTY_ROOM="empty_room"; FUTURE_ME="future_me"; PRESENT_ME="present_me"; PAST_ME="past_me"; ALTERNATIVE_LIFE="alternative_life"; REFLECTION="reflection"
class InputMode(str,enum.Enum): VISUAL="visual"; STRUCTURED="structured"; TEXT="text"; VOICE="voice"
class EvidenceType(str,enum.Enum): SUPPORT="support"; CONTRADICT="contradict"; CONTEXTUAL="contextual"
class EvidenceStrength(str,enum.Enum): WEAK="weak"; MODERATE="moderate"; STRONG="strong"
class PatternStatus(str,enum.Enum): UNKNOWN="unknown"; EMERGING="emerging"; QUESTIONED="questioned"; REPEATED="repeated"; REJECTED="rejected"
class StrandStatus(str,enum.Enum): AI_PROPOSED="ai_proposed"; QUESTIONED="questioned"; USER_CONFIRMED="user_confirmed"; USER_DEFINED="user_defined"; RETIRED="retired"

class User(Base):
    __tablename__="users"
    id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); display_name:Mapped[str|None]=mapped_column(String(120)); current_phase:Mapped[Phase]=mapped_column(Enum(Phase),default=Phase.MIRROR); mirror_level:Mapped[int]=mapped_column(Integer,default=1); preferred_language:Mapped[str]=mapped_column(String(32),default="en"); accessibility_preferences:Mapped[dict]=mapped_column(JSON,default=dict); dna_consent:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
    interests=orm_relationship("MirrorInterest",back_populates="user",cascade="all, delete-orphan"); dna_experiences=orm_relationship("DNAExperience",back_populates="user",cascade="all, delete-orphan"); evidence_items=orm_relationship("Evidence",back_populates="user",cascade="all, delete-orphan"); patterns=orm_relationship("Pattern",back_populates="user",cascade="all, delete-orphan"); dna_strands=orm_relationship("DNAStrand",back_populates="user",cascade="all, delete-orphan"); life_chapters=orm_relationship("LifeChapter",back_populates="user",cascade="all, delete-orphan")
class MirrorInterest(Base):
    __tablename__="mirror_interests"; __table_args__=(UniqueConstraint("user_id","category","name",name="uq_user_interest"),)
    id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); category:Mapped[str]=mapped_column(String(64)); name:Mapped[str]=mapped_column(String(200)); source:Mapped[str]=mapped_column(String(64),default="explicit_user"); purpose:Mapped[str]=mapped_column(String(32),default=DataPurpose.ENTERTAINMENT.value); dna_allowed:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); user=orm_relationship("User",back_populates="interests")
class DNAExperience(Base):
    __tablename__="dna_experiences"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); experience_type:Mapped[ExperienceType]=mapped_column(Enum(ExperienceType)); input_mode:Mapped[InputMode]=mapped_column(Enum(InputMode)); raw_response:Mapped[dict]=mapped_column(JSON,default=dict); purpose:Mapped[str]=mapped_column(String(32),default=DataPurpose.SELF_DISCOVERY.value); consent_for_analysis:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user=orm_relationship("User",back_populates="dna_experiences"); evidence_items=orm_relationship("Evidence",back_populates="experience",cascade="all, delete-orphan")
class Evidence(Base):
    __tablename__="evidence"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); experience_id:Mapped[str|None]=mapped_column(ForeignKey("dna_experiences.id",ondelete="CASCADE"),index=True); source_type:Mapped[str]=mapped_column(String(64)); source_reference:Mapped[dict]=mapped_column(JSON,default=dict); purpose:Mapped[str]=mapped_column(String(32),default=DataPurpose.SELF_DISCOVERY.value); candidate_concept:Mapped[str]=mapped_column(String(200),index=True); evidence_type:Mapped[EvidenceType]=mapped_column(Enum(EvidenceType)); normalized_summary:Mapped[str]=mapped_column(Text); original_text:Mapped[str|None]=mapped_column(Text); strength:Mapped[EvidenceStrength]=mapped_column(Enum(EvidenceStrength),default=EvidenceStrength.WEAK); user_confirmed:Mapped[bool|None]=mapped_column(Boolean); embedding_ref:Mapped[str|None]=mapped_column(String(128)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); user=orm_relationship("User",back_populates="evidence_items"); experience=orm_relationship("DNAExperience",back_populates="evidence_items"); pattern_links=orm_relationship("PatternEvidence",back_populates="evidence",cascade="all, delete-orphan")
class Pattern(Base):
    __tablename__="patterns"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); ai_label:Mapped[str]=mapped_column(String(200)); description:Mapped[str|None]=mapped_column(Text); status:Mapped[PatternStatus]=mapped_column(Enum(PatternStatus),default=PatternStatus.UNKNOWN); support_count:Mapped[int]=mapped_column(Integer,default=0); contradiction_count:Mapped[int]=mapped_column(Integer,default=0); source:Mapped[str]=mapped_column(String(64),default="ai_hypothesis"); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); user=orm_relationship("User",back_populates="patterns"); evidence_links=orm_relationship("PatternEvidence",back_populates="pattern",cascade="all, delete-orphan"); dna_strands=orm_relationship("DNAStrand",back_populates="pattern")
class PatternEvidence(Base):
    __tablename__="pattern_evidence"; __table_args__=(UniqueConstraint("pattern_id","evidence_id",name="uq_pattern_evidence"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); pattern_id:Mapped[str]=mapped_column(ForeignKey("patterns.id",ondelete="CASCADE"),index=True); evidence_id:Mapped[str]=mapped_column(ForeignKey("evidence.id",ondelete="CASCADE"),index=True); relationship:Mapped[EvidenceType]=mapped_column(Enum(EvidenceType)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); pattern=orm_relationship("Pattern",back_populates="evidence_links"); evidence=orm_relationship("Evidence",back_populates="pattern_links")
class DNAStrand(Base):
    __tablename__="dna_strands"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); pattern_id:Mapped[str|None]=mapped_column(ForeignKey("patterns.id",ondelete="SET NULL"),index=True); ai_original_label:Mapped[str|None]=mapped_column(String(200)); user_label:Mapped[str|None]=mapped_column(String(200)); status:Mapped[StrandStatus]=mapped_column(Enum(StrandStatus),default=StrandStatus.AI_PROPOSED); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); user=orm_relationship("User",back_populates="dna_strands"); pattern=orm_relationship("Pattern",back_populates="dna_strands")
class LifeChapter(Base):
    __tablename__="life_chapters"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uuid_str); user_id:Mapped[str]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); title:Mapped[str]=mapped_column(String(200)); description:Mapped[str|None]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default="active"); started_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); ended_at:Mapped[datetime|None]=mapped_column(DateTime); user=orm_relationship("User",back_populates="life_chapters")
